<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\premium_search\Event\AlterSearchSnippetEvent;

/**
 * Implements hook_locale_translation_projects_alter().
 *
 * Convince the module to look in the module folder, instead on drupal.org
 * for translations.
 */
function premium_headless_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('premium_headless')->getPath();
  $projects['premium_headless']['info']['interface translation server pattern'] = $path . '/translations/%language.po';
}

/**
 * Add libraries to specific elements.
 *
 * @param array $types
 *   An associative array with structure identical to that of the return value
 *   of \Drupal\Core\Render\ElementInfoManagerInterface::getInfo().
 */
function premium_headless_element_info_alter(array &$types) {
  if (isset($types['layout_builder'])) {
    $types['layout_builder']['#attached']['library'][] = 'premium_headless_theme/layout-builder';
  }
}
